### ISSUE TITLE
Remove duplicates after c625333

### ISSUE THREAD

**Issue by maelnor** [chaosphere2112/TextCommands#2]
I've encountered a problem after commit c625333, because os.linesep is '\r\n' but sublime returns lines delimited by '\n'. Is there any reason to use os.linesep?

Win7 x64, st 2.0.1 b2217 and st 3 b3022

**Comment by chaosphere2112** [comment]
Thanks for reporting this!

I've just pushed an update that should address this issue... I've switched over to using sublime.view.split_by_newlines(region), and joining with "\n".  I had switched over to os.linesep because I was unaware that Sublime took care of newlines automatically.  This should hopefully solve the problem.

Let me know if the fix works once you get the update, and I'll close the issue.

**Comment by maelnor** [comment]
Thanks, now it works as expected.
